### ISSUE TITLE
Example 321 model.

### ISSUE THREAD

**Issue by Jnsumba** [dd-harp/exDE#36]
When we try to run the R-code for the 321 model, we get the following error; "Error in pars$beta %*% diag(f * q, nrow = pars$nPatches) : 
non-conformable arguments."
see our code:
# 5-3-4 example

rm(list=ls());gc()
library(deSolve)
library(expm)
library(MASS)
source(here::here("Sean/xDE-src/xDE.R"))

# for plotting
library(data.table)
library(ggplot2)

# global parameter object
params <- list(
  nHabitats = 3,
  nPatches = 2,
  nStrata = 1
)

# Aquatic parameters
L0 <- rep(1, params$nHabitats)

Lpar <- list()
class(Lpar) <- 'basic'

Lpar$L0 <- L0
Lpar$psi <- rep(1/8, params$nHabitats)
Lpar$phi <- rep(1/8, params$nHabitats)
Lpar$theta <- c(1/10,  1/40,  1/10) 

# Adult parameters
g <- rep(1/12, params$nPatches) 
sigma <- rep(1/12/2, params$nPatches) 
calK <- t(matrix(
  c(c(0, 1), 
    c(1, 0)), 2, 2))
f <- rep(1/3, params$nPatches) 
q <- rep(0.9, params$nPatches) 
nu <- c(1/3,1/3)   
eggsPerBatch <- 30 
tau <- 12 
M0 <- rep(100, params$nPatches)
G0 <- rep(10, params$nPatches)
Y0 <- rep(1, params$nPatches)
Z0 <- rep(0, params$nPatches)
Omega <- diag(g) + (diag(1,params$nPatches)-calK) %*% diag(sigma)
OmegaEIP <- expm::expm(-Omega*tau)

MYZpar <- list()
class(MYZpar) <- c('RM', 'RM_ode')

MYZpar$Omega <- Omega
MYZpar$OmegaEIP <- OmegaEIP
MYZpar$f <- f
MYZpar$q <- q
MYZpar$nu <- nu
MYZpar$eggsPerBatch <- eggsPerBatch
MYZpar$M0 <- M0
MYZpar$G0 <- G0
MYZpar$Y0 <- Y0
MYZpar$Z0 <- Z0

# Human parameters
H <- 100
X0 <- 0.2*H
r <- rep(1/200, params$nStrata)
b <- rep(0.55, params$nStrata) 
c <- c(.02) 

calJ <-0.1
Theta <- 0.15

W <- Theta*H
beta <-Theta*solve(W)

Xpar <- list()
class(Xpar) <- "SIS"
Xpar$b <- b
Xpar$c <- c
Xpar$r <- r
Xpar$H <- H
Xpar$X0 <- as.vector(X0)

# Biting distribution matrix
params$beta <- beta
params$betaT <- t(beta)

# Aquatic habitat membership matrix
Hmembership <- c(1,2,2)  
calN <- matrix(0, params$nPatches, params$nHabitats)
ix <- cbind(Hmembership, 1:params$nHabitats)
calN[ix] <- 1
params$calN <- calN

# Egg dispersal matrix
xi <- matrix(c(0.2, .8, .2), 3, 1) 
calU <- t(calN %*% diag(as.vector(xi)))
params$calU <- calU

# component parameter objects
params$MYZpar <- MYZpar
params$Lpar <- Lpar
params$Xpar <- Xpar

params <- make_indices(params)

# initial conditions
y <- rep(NaN, max(params$X_ix))
y[params$L_ix] <- as.vector(L0)
y[params$M_ix] <- as.vector(M0)
y[params$G_ix] <- as.vector(G0)
y[params$Y_ix] <- as.vector(Y0)
y[params$Z_ix] <- as.vector(Z0)
y[params$X_ix] <- as.vector(X0)

# solve it!
out <- deSolve::ode(y = y, times = 0:365, func = generalized_spatial_diffeqn, parms = params, method = "lsoda")

colnames(out)[params$L_ix+1] <- paste0('L_', 1:params$nHabitats)
colnames(out)[params$M_ix+1] <- paste0('M_', 1:params$nPatches)
colnames(out)[params$G_ix+1] <- paste0('G_', 1:params$nPatches)
colnames(out)[params$Y_ix+1] <- paste0('Y_', 1:params$nPatches)
colnames(out)[params$Z_ix+1] <- paste0('Z_', 1:params$nPatches)
colnames(out)[params$X_ix+1] <- paste0('X_', 1:params$nStrata)

out <- as.data.table(out)
out <- melt(out, id.vars = 'time')
out[, c("Component", "Stratification") := tstrsplit(variable, '_', fixed = TRUE)]
out[, variable := NULL]

ggplot(data = out, mapping = aes(x = time, y = value, color = Stratification)) +
  geom_line() +
  facet_wrap(. ~ Component, scales = 'free') +
  theme_bw()

**Comment by slwu89** [comment]
Hi @Jnsumba! Thank you for sharing the example with us!

Sorry for any confusion, to use the library, please first install it from this repo, which you can do quickly with:

```r
library(devtools)
devtools::install_github("dd-harp/exDE")
```

Instead of using the file in RAMP-model-library repo. That file is just some early work in progress and may not work properly. After installing the "exDE" package, your example (with a few small changes) works and produces output:

```r
# 5-3-4 example
rm(list=ls());gc()
library(deSolve)
library(expm)
library(MASS)
library(exDE)

# for plotting
library(data.table)
library(ggplot2)

# global parameter object
params <- list(
  nHabitats = 3,
  nPatches = 2,
  nStrata = 1
)

# Aquatic parameters
L0 <- rep(1, params$nHabitats)

Lpar <- list()
class(Lpar) <- 'basic'

Lpar$L0 <- L0
Lpar$psi <- rep(1/8, params$nHabitats)
Lpar$phi <- rep(1/8, params$nHabitats)
Lpar$theta <- c(1/10, 1/40, 1/10)

# Adult parameters
g <- rep(1/12, params$nPatches)
sigma <- rep(1/12/2, params$nPatches)
calK <- t(matrix(
  c(c(0, 1),
    c(1, 0)), 2, 2))
f <- rep(1/3, params$nPatches)
q <- rep(0.9, params$nPatches)
nu <- c(1/3,1/3)
eggsPerBatch <- 30
tau <- 12
M0 <- rep(100, params$nPatches)
G0 <- rep(10, params$nPatches)
Y0 <- rep(1, params$nPatches)
Z0 <- rep(0, params$nPatches)
Omega <- diag(g) + (diag(1,params$nPatches)-calK) %*% diag(sigma)
OmegaEIP <- expm::expm(-Omega*tau)

MYZpar <- list()
class(MYZpar) <- c('RM', 'RM_ode')

MYZpar$Omega <- Omega
MYZpar$OmegaEIP <- OmegaEIP
MYZpar$f <- f
MYZpar$q <- q
MYZpar$nu <- nu
MYZpar$eggsPerBatch <- eggsPerBatch
MYZpar$M0 <- M0
MYZpar$G0 <- G0
MYZpar$Y0 <- Y0
MYZpar$Z0 <- Z0

# Human parameters
H <- 100
X0 <- 0.2*H
r <- rep(1/200, params$nStrata)
b <- rep(0.55, params$nStrata)
c <- c(.02)

# calJ <- 0.1
# Theta <- 0.15

Psi <- matrix(rep(1/params$nPatches, params$nPatches), nrow = params$nPatches, ncol = 1)

W <- Psi %*% H
beta <- t(Psi) %*% diag(1/as.vector(W))

Xpar <- list()
class(Xpar) <- "SIS"
Xpar$b <- b
Xpar$c <- c
Xpar$r <- r
Xpar$H <- H
Xpar$X0 <- as.vector(X0)

# Biting distribution matrix
params$beta <- beta
params$betaT <- t(beta)

# Aquatic habitat membership matrix
Hmembership <- c(1,2,2)
calN <- matrix(0, params$nPatches, params$nHabitats)
ix <- cbind(Hmembership, 1:params$nHabitats)
calN[ix] <- 1
params$calN <- calN

# Egg dispersal matrix
xi <- matrix(c(0.2, .8, .2), 3, 1)
calU <- t(calN %*% diag(as.vector(xi)))
params$calU <- calU

# component parameter objects
params$MYZpar <- MYZpar
params$Lpar <- Lpar
params$Xpar <- Xpar

params <- make_indices(params)

# initial conditions
y <- rep(NaN, max(params$X_ix))
y[params$L_ix] <- as.vector(L0)
y[params$M_ix] <- as.vector(M0)
y[params$G_ix] <- as.vector(G0)
y[params$Y_ix] <- as.vector(Y0)
y[params$Z_ix] <- as.vector(Z0)
y[params$X_ix] <- as.vector(X0)

# solve it!
out <- deSolve::ode(y = y, times = 0:365, func = xDE_diffeqn, parms = params, method = "lsoda")

colnames(out)[params$L_ix+1] <- paste0('L_', 1:params$nHabitats)
colnames(out)[params$M_ix+1] <- paste0('M_', 1:params$nPatches)
colnames(out)[params$G_ix+1] <- paste0('G_', 1:params$nPatches)
colnames(out)[params$Y_ix+1] <- paste0('Y_', 1:params$nPatches)
colnames(out)[params$Z_ix+1] <- paste0('Z_', 1:params$nPatches)
colnames(out)[params$X_ix+1] <- paste0('X_', 1:params$nStrata)

out <- as.data.table(out)
out <- melt(out, id.vars = 'time')
out[, c("Component", "Stratification") := tstrsplit(variable, '_', fixed = TRUE)]
out[, variable := NULL]

ggplot(data = out, mapping = aes(x = time, y = value, color = Stratification)) +
  geom_line() +
  facet_wrap(. ~ Component, scales = 'free') +
  theme_bw()
```

**Comment by Jnsumba** [comment]
Thanks Sean.

**Comment by Jnsumba** [comment]
rm(list=ls());gc()
library(deSolve)
library(expm)
library(MASS)
source(here::here("Sean/xDE-src/xDE.R"))

# for plotting
library(data.table)
library(ggplot2)

# global parameter object
params <- list(
  nHabitats = 3,
  nPatches = 2,
  nStrata = 1
)

# Aquatic parameters
L0 <- rep(1, params$nHabitats)

Lpar <- list()
class(Lpar) <- 'basic'

Lpar$L0 <- L0
Lpar$psi <- rep(1/8, params$nHabitats)
Lpar$phi <- rep(1/8, params$nHabitats)
Lpar$theta <- c(1/10,  1/40,  1/10) 


# Adult parameters
g <- rep(1/12, params$nPatches) 
sigma <- rep(1/12/2, params$nPatches) 
calK <- t(matrix(
  c(c(0, 1), 
    c(1, 0)), 2, 2))
f <- rep(1/3, params$nPatches) 
q <- rep(0.9, params$nPatches) 
nu <- c(1/3,1/3)   
eggsPerBatch <- 30 
tau <- 12 
M0 <- rep(100, params$nPatches)
G0 <- rep(10, params$nPatches)
Y0 <- rep(1, params$nPatches)
Z0 <- rep(0, params$nPatches)
Omega <- diag(g) + (diag(1,params$nPatches)-calK) %*% diag(sigma)
OmegaEIP <- expm::expm(-Omega*tau)

MYZpar <- list()
class(MYZpar) <- c('RM', 'RM_ode')

MYZpar$Omega <- Omega
MYZpar$OmegaEIP <- OmegaEIP
MYZpar$f <- f
MYZpar$q <- q
MYZpar$nu <- nu
MYZpar$eggsPerBatch <- eggsPerBatch
MYZpar$M0 <- M0
MYZpar$G0 <- G0
MYZpar$Y0 <- Y0
MYZpar$Z0 <- Z0

# Human parameters
H <- 100
X0 <- 0.2*H
r <- rep(1/200, params$nStrata)
b <- rep(0.55, params$nStrata) 
c <- c(.02) 

# calJ <- 0.1
# Theta <- 0.15

calJ <- t(matrix(
  c(c(1),
    c(1)), 2, 1
))
Theta <- t(matrix(
  c(c(0.3),
    c(0.7)),2, 1))

#Psi <- matrix(rep(1/params$nPatches, params$nPatches), nrow = params$nPatches, ncol = 1)
#W <- Psi %*% H
#beta <- t(Psi) %*% diag(1/as.vector(W))

W <- t(Theta) %*% H
beta <- Theta %*% diag(1/as.vector(W))#diag_inverse(W) 

Xpar <- list()
class(Xpar) <- "SIS"
Xpar$b <- b
Xpar$c <- c
Xpar$r <- r
Xpar$H <- H
Xpar$X0 <- as.vector(X0)

# Biting distribution matrix
params$beta <- beta
params$betaT <- t(beta)

# Aquatic habitat membership matrix
Hmembership <- c(1,2,2)  
calN <- matrix(0, params$nPatches, params$nHabitats)
ix <- cbind(Hmembership, 1:params$nHabitats)
calN[ix] <- 1
params$calN <- calN

# Egg dispersal matrix
xi <- matrix(c(0.2, .8, .2), 3, 1) 
calU <- t(calN %*% diag(as.vector(xi)))
params$calU <- calU


# component parameter objects
params$MYZpar <- MYZpar
params$Lpar <- Lpar
params$Xpar <- Xpar

params <- make_indices(params)


# initial conditions
y <- rep(NaN, max(params$X_ix))
y[params$L_ix] <- as.vector(L0)
y[params$M_ix] <- as.vector(M0)
y[params$G_ix] <- as.vector(G0)
y[params$Y_ix] <- as.vector(Y0)
y[params$Z_ix] <- as.vector(Z0)
y[params$X_ix] <- as.vector(X0)

# solve it!
out <- deSolve::ode(y = y, times = 0:365, func = xDE_diffeqn, parms = params, method = "lsoda")

colnames(out)[params$L_ix+1] <- paste0('L_', 1:params$nHabitats)
colnames(out)[params$M_ix+1] <- paste0('M_', 1:params$nPatches)
colnames(out)[params$G_ix+1] <- paste0('G_', 1:params$nPatches)
colnames(out)[params$Y_ix+1] <- paste0('Y_', 1:params$nPatches)
colnames(out)[params$Z_ix+1] <- paste0('Z_', 1:params$nPatches)
colnames(out)[params$X_ix+1] <- paste0('X_', 1:params$nStrata)

out <- as.data.table(out)
out <- melt(out, id.vars = 'time')
out[, c("Component", "Stratification") := tstrsplit(variable, '_', fixed = TRUE)]
out[, variable := NULL]

ggplot(data = out, mapping = aes(x = time, y = value, color = Stratification)) +
  geom_line() +
  facet_wrap(. ~ Component, scales = 'free') +
  theme_bw()

We have noted that psi allocates the same time at risk for the two patches. We have tried it with the other examples (5-3-4, 3-2-2) and it does the same thing. Just thinking that the time spent at risk in the patches might be different so we played with the theta matrix and  CalJ in the code a bit as in this example so that we could set different times at risk. Please let us know what you think about it.

**Comment by slwu89** [comment]
Hi @Jnsumba, yes you are right, in the example I just allocated time at risk equally across all the patches; it is not a very good model for actual use, just a easy to understand example. I think that if you have any data for a specific scenario, you should use a version of Psi that realistically allocates time at risk across the patches.

**Comment by slwu89** [comment]
Here's an example of a scenario where we used travel data from Bioko Island to construct a "Psi" matrix (called Time at Risk matrix in the paper), and then used that matrix as a parameter in the kind of model that can be built in exDE: https://malariajournal.biomedcentral.com/articles/10.1186/s12936-021-03893-x

**Comment by smitdave** [comment]
This has been resolved.
