### ISSUE TITLE
Garki model

### ISSUE THREAD

**Issue by slwu89** [dd-harp/exDE#85]
the Garki model of human disease dynamics will be a great medium-sized chunk of work that could be added to the human component $\mathcal{X}$. It will be a nice test to see how a few people can collaborate to bring it to fruition. The model is described in ["A malaria model tested in the African savannah"](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2481186/). @smitdave I'm not sure if you have other/preferred references for the model.

**Comment by smitdave** [comment]
A decision was made to not expand the set of base models. New models are being added to ramp.library
